server:
  port: 8080

spring:
  application:
    name: admin-module
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/linkr_admin?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: Xing@1225

logging:
  level:
    com.aleks.linkrmix.admin: DEBUG
    org.springframework.security: DEBUG
